### ISSUE TITLE
Missing Secp256k1.NET assembly

### ISSUE THREAD

**Issue by dthorpe** [pmlyon/BitSharp#22]
BitSharp.Core project references a Secp256k1.NET assembly which is not included in the solution files and is not a Nuget package.

**Comment by pmlyon** [comment]
Were you in 32-bit? I only have the 64-bit DLL for it, so it will get ignored in 32-bit mode and won't fail the compile if it's missing.

**Comment by pmlyon** [comment]
libbitcoin-consensus is now used for executing scripts.
